export const dummyChatData = [
  {
    id: 1,
    userName: "Chidi",
    read: false,
    messages: [
      {
        message: "Hello Emy, I was wondering if we could got to the movies to",
        read: false,
        type: "sent",
        createdAt: "2022-10-20T14:48:00",
        id: 1,
      },
      {
        message: "Lastma just hold me",
        read: false,
        type: "sent",
        createdAt: "2022-10-20T15:48:03",
        id: 2,
      },
      {
        message: "Okay, kid bro",
        read: false,
        type: "received",
        createdAt: "2022-10-20T14:49:03",
        id: 3,
      },
      {
        message: "Send your aza",
        read: false,
        type: "received",
        createdAt: "2022-10-20T14:48:01",
        id: 4,
      },
    ],
  },
  {
    id: 2,
    userName: "Ama",
    read: false,
    messages: [
      {
        message: "Hello Emy, I was wondering if we could got to the movies to",
        read: false,
        type: "sent",
        createdAt: "2022-10-20T14:48:00",
        id: 1,
      },
      {
        message: "50%, Sis",
        read: false,
        type: "sent",
        createdAt: "2022-10-20T14:49:00",
        id: 2,
      },
      {
        message: "How far with the json? Are you done?",
        read: false,
        type: "received",
        createdAt: "2022-10-20T14:48:00",
        id: 3,
      },
      {
        message: "🙌🏼",
        read: false,
        type: "received",
        createdAt: "2022-10-20T14:49:10",
        id: 4,
      },
    ],
  },
  {
    id: 3,
    userName: "Ama",
    read: false,
    messages: [
      {
        message: "Hello Emy, I was wondering if we could got to the movies to",
        read: false,
        type: "sent",
        createdAt: "2022-10-20T14:48:00",
        id: 1,
      },
      {
        message: "50%, Sis",
        read: false,
        type: "sent",
        createdAt: "2022-10-20T14:49:00",
        id: 2,
      },
      {
        message: "How far with the json? Are you done?",
        read: false,
        type: "received",
        createdAt: "2022-10-20T14:48:00",
        id: 3,
      },
      {
        message: "🙌🏼",
        read: false,
        type: "received",
        createdAt: "2022-10-20T14:49:10",
        id: 4,
      },
    ],
  },
  {
    id: 4,
    userName: "Ama",
    read: false,
    messages: [
      {
        message: "Hello Emy, I was wondering if we could got to the movies to",
        read: false,
        type: "sent",
        createdAt: "2022-10-20T14:48:00",
        id: 1,
      },
      {
        message: "50%, Sis",
        read: false,
        type: "sent",
        createdAt: "2022-10-20T14:49:00",
        id: 2,
      },
      {
        message: "How far with the json? Are you done?",
        read: false,
        type: "received",
        createdAt: "2022-10-20T14:48:00",
        id: 3,
      },
      {
        message: "🙌🏼",
        read: false,
        type: "received",
        createdAt: "2022-10-20T14:49:10",
        id: 4,
      },
    ],
  },
  {
    id: 5,
    userName: "Ama",
    read: false,
    messages: [
      {
        message: "Hello Emy, I was wondering if we could got to the movies to",
        read: false,
        type: "sent",
        createdAt: "2022-10-20T14:48:00",
        id: 1,
      },
      {
        message: "50%, Sis",
        read: false,
        type: "sent",
        createdAt: "2022-10-20T14:49:00",
        id: 2,
      },
      {
        message: "How far with the json? Are you done?",
        read: false,
        type: "received",
        createdAt: "2022-10-20T14:48:00",
        id: 3,
      },
      {
        message: "🙌🏼",
        read: false,
        type: "received",
        createdAt: "2022-10-20T14:49:10",
        id: 4,
      },
    ],
  },
  {
    id: 6,
    userName: "Ama",
    read: false,
    messages: [
      {
        message: "Hello Emy, I was wondering if we could got to the movies to",
        read: false,
        type: "sent",
        createdAt: "2022-10-20T14:48:00",
        id: 1,
      },
      {
        message: "50%, Sis",
        read: false,
        type: "sent",
        createdAt: "2022-10-20T14:49:00",
        id: 2,
      },
      {
        message: "How far with the json? Are you done?",
        read: false,
        type: "received",
        createdAt: "2022-10-20T14:48:00",
        id: 3,
      },
      {
        message: "🙌🏼",
        read: false,
        type: "received",
        createdAt: "2022-10-20T14:49:10",
        id: 4,
      },
    ],
  },
  {
    id: 7,
    userName: "Ama",
    read: false,
    messages: [
      {
        message: "Hello Emy, I was wondering if we could got to the movies to",
        read: false,
        type: "sent",
        createdAt: "2022-10-20T14:48:00",
        id: 1,
      },
      {
        message: "50%, Sis",
        read: false,
        type: "sent",
        createdAt: "2022-10-20T14:49:00",
        id: 2,
      },
      {
        message: "How far with the json? Are you done?",
        read: false,
        type: "received",
        createdAt: "2022-10-20T14:48:00",
        id: 3,
      },
      {
        message: "🙌🏼",
        read: false,
        type: "received",
        createdAt: "2022-10-20T14:49:10",
        test: "fjfj",
        id: 4,
      },
    ],
  },
];
